---
name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: make install
      - run: make compile
      - run: make themes

      - name: Publish to Visual Studio Marketplace
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Post-release sync
        run: ./utils/ci/sync.sh
        if: success()
