---
name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - id: cache
        name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ runner.OS }}-${{ hashFiles('package-lock.json') }}
      - run: touch node_modules
        if: steps.cache.outputs.cache-hit == 'true'

      - run: make install
      - run: make precompile
      - run: make themes

      - name: Publish to Visual Studio Marketplace
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Post-release sync
        run: ./utils/ci/sync.sh
        if: success()
