---
name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: make install
      - run: make compile
      - run: make lint
      - run: make themes
